apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-v2
  labels:
    app: demo
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
      version: v2
  template:
    metadata:
      labels:
        app: demo
        version: v2
    spec:
      containers:
      - name: demo
        image: larstobi/http-echo:0.2.4
        args:
        - -listen=:80
        - -text="$(DEPLOYMENT_NAME), pod-> $(POD_NAME)"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['version']